// モックデータ — Firebase 接続前の開発・UIテスト用
import type { Room, Club, User, ScheduledEvent } from '@/types'

// モックユーザー
export const mockCurrentUser: User = {
  id: 'user_current',
  username: 'hiroki_dev',
  displayName: 'Hiroki',
  bio: 'Connect Club 開発者 🎙️',
  avatarUrl: null,
  followers: ['u1', 'u2', 'u3'],
  following: ['u1', 'u4'],
  clubIds: ['club1', 'club2'],
  createdAt: new Date(),
}

// モック部屋一覧
export const mockRooms: Room[] = [
  {
    id: 'room1',
    name: 'Webスタートアップを語る夜 🚀',
    description: '今週のProduct Huntで話題になったプロダクトをみんなで議論しよう！',
    hostId: 'u1',
    hostName: 'Yuki Tanaka',
    hostAvatar: null,
    clubId: 'club1',
    clubName: 'Tech Tokyo',
    isPublic: true,
    tags: ['スタートアップ', 'テック', 'プロダクト'],
    participantCount: 24,
    speakers: [
      { userId: 'u1', username: 'yuki_t', displayName: 'Yuki Tanaka', avatarUrl: null, role: 'host', isMuted: false, isSpeaking: true, handRaised: false },
      { userId: 'u2', username: 'maria_k', displayName: 'Maria Kim', avatarUrl: null, role: 'speaker', isMuted: false, isSpeaking: false, handRaised: false },
      { userId: 'u3', username: 'alex_w', displayName: 'Alex Wang', avatarUrl: null, role: 'speaker', isMuted: true, isSpeaking: false, handRaised: false },
    ],
    listeners: Array.from({ length: 21 }, (_, i) => ({
      userId: `listener_${i}`,
      username: `user_${i}`,
      displayName: `User ${i + 1}`,
      avatarUrl: null,
      role: 'listener' as const,
      isMuted: true,
      isSpeaking: false,
      handRaised: i === 2,
    })),
    livekitRoomName: 'livekit_room1',
    createdAt: new Date(Date.now() - 45 * 60 * 1000),
  },
  {
    id: 'room2',
    name: 'AI時代のデザイン思考 🎨',
    description: 'Figma AI、Midjourney、Framerで実際どう変わった？デザイナーたちが本音で語る',
    hostId: 'u4',
    hostName: 'Sara Kimura',
    hostAvatar: null,
    clubId: 'club2',
    clubName: 'Design Circle',
    isPublic: true,
    tags: ['デザイン', 'AI', 'UX'],
    participantCount: 87,
    speakers: [
      { userId: 'u4', username: 'sara_k', displayName: 'Sara Kimura', avatarUrl: null, role: 'host', isMuted: false, isSpeaking: true, handRaised: false },
      { userId: 'u5', username: 'jake_m', displayName: 'Jake Mori', avatarUrl: null, role: 'speaker', isMuted: false, isSpeaking: true, handRaised: false },
      { userId: 'u6', username: 'lisa_n', displayName: 'Lisa Nakamura', avatarUrl: null, role: 'speaker', isMuted: true, isSpeaking: false, handRaised: false },
      { userId: 'u7', username: 'tom_s', displayName: 'Tom Suzuki', avatarUrl: null, role: 'speaker', isMuted: true, isSpeaking: false, handRaised: false },
    ],
    listeners: Array.from({ length: 83 }, (_, i) => ({
      userId: `listener2_${i}`,
      username: `listener_${i}`,
      displayName: `Listener ${i + 1}`,
      avatarUrl: null,
      role: 'listener' as const,
      isMuted: true,
      isSpeaking: false,
      handRaised: false,
    })),
    livekitRoomName: 'livekit_room2',
    createdAt: new Date(Date.now() - 18 * 60 * 1000),
  },
  {
    id: 'room3',
    name: '🎵 Lo-fi & 深夜コーディングタイム',
    description: 'みんなで作業しながら話すゆるい部屋。何を作ってる？',
    hostId: 'u8',
    hostName: 'Rin Hayashi',
    hostAvatar: null,
    clubId: null,
    clubName: null,
    isPublic: true,
    tags: ['作業', 'コーディング', 'Lo-fi'],
    participantCount: 12,
    speakers: [
      { userId: 'u8', username: 'rin_h', displayName: 'Rin Hayashi', avatarUrl: null, role: 'host', isMuted: false, isSpeaking: false, handRaised: false },
    ],
    listeners: Array.from({ length: 11 }, (_, i) => ({
      userId: `listener3_${i}`,
      username: `coder_${i}`,
      displayName: `Coder ${i + 1}`,
      avatarUrl: null,
      role: 'listener' as const,
      isMuted: true,
      isSpeaking: false,
      handRaised: false,
    })),
    livekitRoomName: 'livekit_room3',
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000),
  },
  {
    id: 'room4',
    name: 'Web3とNFTはどこへ行く？ 2026年の展望',
    description: '冷静にWeb3の現状を整理して、次のナラティブを探る部屋',
    hostId: 'u9',
    hostName: 'Kenji Ota',
    hostAvatar: null,
    clubId: 'club3',
    clubName: 'Crypto Japan',
    isPublic: true,
    tags: ['Web3', 'クリプト', '投資'],
    participantCount: 156,
    speakers: [
      { userId: 'u9', username: 'kenji_o', displayName: 'Kenji Ota', avatarUrl: null, role: 'host', isMuted: false, isSpeaking: true, handRaised: false },
      { userId: 'u10', username: 'anna_b', displayName: 'Anna Brown', avatarUrl: null, role: 'speaker', isMuted: false, isSpeaking: false, handRaised: false },
      { userId: 'u11', username: 'chen_l', displayName: 'Chen Liu', avatarUrl: null, role: 'speaker', isMuted: false, isSpeaking: false, handRaised: false },
      { userId: 'u12', username: 'yoshi_f', displayName: 'Yoshida Fumio', avatarUrl: null, role: 'speaker', isMuted: false, isSpeaking: true, handRaised: false },
      { userId: 'u13', username: 'maya_r', displayName: 'Maya Rodriguez', avatarUrl: null, role: 'speaker', isMuted: true, isSpeaking: false, handRaised: false },
    ],
    listeners: Array.from({ length: 151 }, (_, i) => ({
      userId: `listener4_${i}`,
      username: `user4_${i}`,
      displayName: `User ${i + 1}`,
      avatarUrl: null,
      role: 'listener' as const,
      isMuted: true,
      isSpeaking: false,
      handRaised: i % 7 === 0,
    })),
    livekitRoomName: 'livekit_room4',
    createdAt: new Date(Date.now() - 8 * 60 * 1000),
  },
]

// モッククラブ一覧
export const mockClubs: Club[] = [
  {
    id: 'club1',
    slug: 'tech-tokyo',
    name: 'Tech Tokyo',
    description: '東京のテック・スタートアップシーンを語り合うコミュニティ',
    imageUrl: null,
    tags: ['テック', 'スタートアップ', '東京'],
    memberCount: 1240,
    followCount: 3420,
    moderatorIds: ['u1'],
    memberIds: ['u1', 'u2', 'user_current'],
    isFollowing: true,
    createdAt: new Date('2023-01-15'),
  },
  {
    id: 'club2',
    slug: 'design-circle',
    name: 'Design Circle',
    description: 'デザイナーのためのデザイナーによるコミュニティ。UI/UX、グラフィック、モーション',
    imageUrl: null,
    tags: ['デザイン', 'UI/UX', 'クリエイティブ'],
    memberCount: 890,
    followCount: 2100,
    moderatorIds: ['u4'],
    memberIds: ['u4', 'u5', 'user_current'],
    isFollowing: true,
    createdAt: new Date('2023-03-20'),
  },
  {
    id: 'club3',
    slug: 'crypto-japan',
    name: 'Crypto Japan',
    description: '日本最大のWeb3・仮想通貨コミュニティ',
    imageUrl: null,
    tags: ['Web3', 'クリプト', 'DeFi'],
    memberCount: 4560,
    followCount: 12000,
    moderatorIds: ['u9'],
    memberIds: ['u9', 'u10'],
    isFollowing: false,
    createdAt: new Date('2022-11-01'),
  },
  {
    id: 'club4',
    slug: 'product-japan',
    name: 'Product Japan',
    description: 'プロダクトマネージャーとプロダクトラバーのためのコミュニティ',
    imageUrl: null,
    tags: ['PM', 'プロダクト', 'ビジネス'],
    memberCount: 2300,
    followCount: 5600,
    moderatorIds: ['u14'],
    memberIds: ['u14'],
    isFollowing: false,
    createdAt: new Date('2023-06-10'),
  },
]

// スケジュールイベント
export const mockEvents: ScheduledEvent[] = [
  {
    id: 'event1',
    title: 'Product Hunt Radio — 週次ラウンドテーブル',
    description: '今週注目のプロダクトをHunterたちと深掘り',
    hostId: 'u1',
    hostName: 'Yuki Tanaka',
    clubId: 'club1',
    clubName: 'Tech Tokyo',
    scheduledAt: new Date(Date.now() + 2 * 60 * 60 * 1000),
    durationMinutes: 60,
    participantCount: 45,
    isJoined: true,
  },
  {
    id: 'event2',
    title: 'AI Weekly — 今週のLLMニュースまとめ',
    description: 'GPT-5、Gemini 2.0、Claude 4...今週も盛りだくさん',
    hostId: 'u4',
    hostName: 'Sara Kimura',
    clubId: null,
    clubName: null,
    scheduledAt: new Date(Date.now() + 24 * 60 * 60 * 1000),
    durationMinutes: 90,
    participantCount: 128,
    isJoined: false,
  },
]
